# Generated by Django 2.1 on 2019-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191120_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('deliver_order', 'Может доставить заказ')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
